FROM python:3.12-bullseye
RUN apt-get update 
RUN apt-get install wkhtmltopdf -y
RUN pip install --no-cache-dir celery jinja2 pdfkit pydantic-settings
WORKDIR app/
# COPY ./app/celery_worker ./celery_worker
CMD ["celery", "-A", "celery_worker.tasks", "worker", "--loglevel=INFO"]

