version: '3'
services:
  api:
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile.dev.app
    ports:
        - '8000:8000'
    volumes:
      - type: bind
        source: /c/Users/Kirill/Desktop/PROGRAMMING/Projects/VK_report_generator/app
        target: /app
    depends_on:
      database:
        condition: service_healthy
    restart: always

  celery:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      TZ: Europe/Moscow
    volumes:
      - type: bind
        source: /c/Users/Kirill/Desktop/PROGRAMMING/Projects/VK_report_generator/app
        target: /app
    depends_on:
      rabbit:
        condition: service_healthy
    restart: always

  rabbit:
    env_file: .env
    image: rabbitmq:3-alpine
    expose:
      - "5672"
    environment:
      TZ: Europe/Moscow
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 10 
    restart: always

  database:
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data
      DB_NAME: related_users
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    image: postgres:15-alpine
    expose:
        - "5432"
    healthcheck:
      test: pg_isready -U ${DATABASE_USER}
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - database_volume:/var/lib/postgresql/data
    restart: always

volumes:
  shared_volume:
  database_volume:

